export const REFRESH_NEWS = 'REFRESH_NEWS';
export const REQUEST_NEWS = 'REQUEST_NEWS';
export const REQUEST_NEWS_SUCCESS = 'REQUEST_NEWS_SUCCESS';
export const REQUEST_NEWS_FAILED = 'REQUEST_NEWS_FAILED';
